In [2]:
import numpy as np

In [4]:
a = np.array([1,3,5,7,9,11], dtype=int)
b_list=[2,4,6,8,10,12]
b = np.array(b_list)
c = np.array([[1.1,2.2,3.3,4.4,5.5,6.6], [7.7,8.8,9.9,10.10,11.11,12.12], [13.13,14.14,15.15,16.16,17.17,0]])

In [3]:
d = np.zeros((4,6))
e = np.ones((3,3,3))

In [4]:
f = np.eye(5)
g = np.empty((5,5))
h = np.arange(0,1,0.1)
h2 = np.arange(10)

i = np.linspace(0,1,20)

In [42]:
print (a)
print ('-----')
print (b)
print ('-----')
print (c)
print ('-----')
print (d)
print ('-----')
print (e)
print ('-----')
print (f)
print ('-----')
print (g)
print ('-----')
print (h)
print (h2)
print ('-----')
print (i)
print ('-----')
type(c)

[ 1  3  5  7  9 11]
-----
[ 2  4  6  8 10 12]
-----
[[[  10.1   10.2   10.3]
  [  20.1   20.2   20.3]
  [  30.1   30.2   30.3]
  [  40.1   40.2   40.3]
  [  50.1   50.2   50.3]]

 [[ 100.1  100.2  100.3]
  [ 200.1  200.2  200.3]
  [ 300.1  300.2  300.3]
  [ 400.1  400.2  400.3]
  [ 500.1  500.2  500.3]]

 [[1000.1 1000.2 1000.3]
  [2000.1 2000.2 2000.3]
  [3000.1 3000.2 3000.3]
  [4000.1 4000.2 4000.3]
  [5000.1 5000.2 5000.3]]]
-----


NameError: name 'd' is not defined

In [6]:
def func_sum_mul_5(i, j):
    return 5 * (i + j)

j = np.fromfunction(func_sum_mul_5, (3,3))

print (j)

[[ 0.  5. 10.]
 [ 5. 10. 15.]
 [10. 15. 20.]]


In [7]:
print(np.arange(0, 3000, 1))

[   0    1    2 ... 2997 2998 2999]


In [8]:
np.set_printoptions(precision=2 ,threshold=1000, edgeitems=5)

In [9]:
print(np.arange(0, 3000, 1))

[   0    1    2    3    4 ... 2995 2996 2997 2998 2999]


одного размера


In [10]:
a + b

array([ 3,  7, 11, 15, 19, 23])

In [11]:
b - a

array([1, 1, 1, 1, 1, 1])

In [12]:
a * b

array([  2,  12,  30,  56,  90, 132])

In [13]:
b / a

array([2.  , 1.33, 1.2 , 1.14, 1.11, 1.09])

In [5]:
a ** b

array([          1,          81,       15625,     5764801,  -808182895,
       -1192716655], dtype=int32)

In [15]:
b % a # При взятии остатка от деления на 0 возвращается 0

array([0, 1, 1, 1, 1, 1], dtype=int32)

In [16]:
b // a

array([2, 1, 1, 1, 1, 1], dtype=int32)

элемент и число

In [17]:
a + 1

array([ 2,  4,  6,  8, 10, 12])

In [18]:
a < 5

array([ True,  True, False, False, False, False])

In [19]:
a[a<5]

array([1, 3])

In [20]:
a.sum()
np.sum(a)

36

slice

In [41]:
a[0]
a[0:2]
a[::-1]

for i in a:
     print(i ** 2)


1
9
25
49
81
121


In [28]:
c.shape

(3, 6)

In [44]:
c

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ,  6.6 ],
       [ 7.7 ,  8.8 ,  9.9 , 10.1 , 11.11, 12.12],
       [13.13, 14.14, 15.15, 16.16, 17.17,  0.  ]])

In [29]:
c.min(axis=0)  # Наименьшее число в каждом столбце
c.min(axis=1)  # Наименьшее число в каждой строке

array([1.1, 7.7, 0. ])

In [9]:
print(c[::-1])
print('-----')
print(c[-1])

[[13.13 14.14 15.15 16.16 17.17  0.  ]
 [ 7.7   8.8   9.9  10.1  11.11 12.12]
 [ 1.1   2.2   3.3   4.4   5.5   6.6 ]]
-----
[13.13 14.14 15.15 16.16 17.17  0.  ]


In [32]:
c[1:3:1]

array([[ 7.7 ,  8.8 ,  9.9 , 10.1 , 11.11, 12.12],
       [13.13, 14.14, 15.15, 16.16, 17.17,  0.  ]])

In [43]:
print(c[2,3])
print(c[(2,3)])
print(c[2][3])

16.16
16.16
16.16


In [45]:
c[:,2]

array([ 3.3 ,  9.9 , 15.15])

In [46]:
c[:2]

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ,  6.6 ],
       [ 7.7 ,  8.8 ,  9.9 , 10.1 , 11.11, 12.12]])

In [50]:
c[1:3,1:3]

array([[ 8.8 ,  9.9 ],
       [14.14, 15.15]])

In [10]:
c

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ,  6.6 ],
       [ 7.7 ,  8.8 ,  9.9 , 10.1 , 11.11, 12.12],
       [13.13, 14.14, 15.15, 16.16, 17.17,  0.  ]])

In [20]:
k = np.array([[[10.1,10.2,10.3],[20.1,20.2,20.3],[30.1,30.2,30.3],[40.1,40.2,40.3],[50.1,50.2,50.3]],
              [[100.1,100.2,100.3],[200.1,200.2,200.3],[300.1,300.2,300.3],[400.1,400.2,400.3],[500.1,500.2,500.3]],
              [[1000.1,1000.2,1000.3],[2000.1,2000.2,2000.3],[3000.1,3000.2,3000.3],[4000.1,4000.2,4000.3],[5000.1,5000.2,5000.3]]])

In [24]:
k.shape

(3, 5, 3)

...

In [38]:
k[0:2,:,:]
k[0:2,...]

array([[[ 10.1,  10.2,  10.3],
        [ 20.1,  20.2,  20.3],
        [ 30.1,  30.2,  30.3],
        [ 40.1,  40.2,  40.3],
        [ 50.1,  50.2,  50.3]],

       [[100.1, 100.2, 100.3],
        [200.1, 200.2, 200.3],
        [300.1, 300.2, 300.3],
        [400.1, 400.2, 400.3],
        [500.1, 500.2, 500.3]]])

In [47]:
for i in k:
    print (i)
    print ('-----')
    for i2 in i:
        print (i2)
        print ('-----')
        for i3 in i2:
            print (i3)
            print ('-----')


[[10.1 10.2 10.3]
 [20.1 20.2 20.3]
 [30.1 30.2 30.3]
 [40.1 40.2 40.3]
 [50.1 50.2 50.3]]
-----
[10.1 10.2 10.3]
-----
10.1
-----
10.2
-----
10.3
-----
[20.1 20.2 20.3]
-----
20.1
-----
20.2
-----
20.3
-----
[30.1 30.2 30.3]
-----
30.1
-----
30.2
-----
30.3
-----
[40.1 40.2 40.3]
-----
40.1
-----
40.2
-----
40.3
-----
[50.1 50.2 50.3]
-----
50.1
-----
50.2
-----
50.3
-----
[[100.1 100.2 100.3]
 [200.1 200.2 200.3]
 [300.1 300.2 300.3]
 [400.1 400.2 400.3]
 [500.1 500.2 500.3]]
-----
[100.1 100.2 100.3]
-----
100.1
-----
100.2
-----
100.3
-----
[200.1 200.2 200.3]
-----
200.1
-----
200.2
-----
200.3
-----
[300.1 300.2 300.3]
-----
300.1
-----
300.2
-----
300.3
-----
[400.1 400.2 400.3]
-----
400.1
-----
400.2
-----
400.3
-----
[500.1 500.2 500.3]
-----
500.1
-----
500.2
-----
500.3
-----
[[1000.1 1000.2 1000.3]
 [2000.1 2000.2 2000.3]
 [3000.1 3000.2 3000.3]
 [4000.1 4000.2 4000.3]
 [5000.1 5000.2 5000.3]]
-----
[1000.1 1000.2 1000.3]
-----
1000.1
-----
1000.2
-----
1000.3
-----
[2000.

In [51]:
for i in k.flat:
    print (i)

10.1
10.2
10.3
20.1
20.2
20.3
30.1
30.2
30.3
40.1
40.2
40.3
50.1
50.2
50.3
100.1
100.2
100.3
200.1
200.2
200.3
300.1
300.2
300.3
400.1
400.2
400.3
500.1
500.2
500.3
1000.1
1000.2
1000.3
2000.1
2000.2
2000.3
3000.1
3000.2
3000.3
4000.1
4000.2
4000.3
5000.1
5000.2
5000.3
