In [1]:
import numpy as np

In [2]:
a = np.array([1,3,5,7,9,11], dtype=int)
b_list=[2,4,6,8,10,12]
b = np.array(b_list)
c = np.array([[1.1,2.2,3.3,4.4,5.5,6.6], [7.7,8.8,9.9,10.10,11.11,12.12], [13.13,14.14,15.15,16.16,17.17,0]])

In [3]:
d = np.zeros((4,6))
e = np.ones((3,3,3))

np.zeros_like(a) # создает zeros той же размерности что и a
np.ones_like(a) # создает ones той же размерности что и a

array([1, 1, 1, 1, 1, 1])

In [8]:


f = np.eye(5)
f1 = np.identity(5)
f2 = np.eye(5, k=1, dtype=float)

f3=b.reshape((3,2)).diagonal()

g = np.empty((5,5))
h = np.arange(0,1,0.1)
h2 = np.arange(10)

i = np.linspace(0,1,20)



In [10]:
print ('--a--')
print (a)
print ('--b--')
print (b)
print ('--c--')
print (c)
print ('--d--')
print (d)
print ('--e--')
print (e)
print ('--f--')
print (f)
print (f1)
print (f2)
print (f3)
print ('-----')
print (g)
print ('-----')
print (h)
print (h2)
print ('-----')
print (i)
print ('-----')
type(c)

--a--
[ 1  3  5  7  9 11]
--b--
[ 2  4  6  8 10 12]
--c--
[[ 1.1   2.2   3.3   4.4   5.5   6.6 ]
 [ 7.7   8.8   9.9  10.1  11.11 12.12]
 [13.13 14.14 15.15 16.16 17.17  0.  ]]
--d--
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
--e--
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
--f--
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[2 8]
-----
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
-----
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0 1 2 3 4 5 6 7 8 9]
-----
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 

numpy.ndarray

In [11]:
def func_sum_mul_5(i, j):
    return 5 * (i + j)

j = np.fromfunction(func_sum_mul_5, (3,3))

print (j)

[[ 0.  5. 10.]
 [ 5. 10. 15.]
 [10. 15. 20.]]


In [12]:
print(np.arange(0, 3000, 1))

[   0    1    2 ... 2997 2998 2999]


In [13]:
np.set_printoptions(precision=2 ,threshold=1000, edgeitems=5)

In [14]:
print(np.arange(0, 3000, 1))

[   0    1    2    3    4 ... 2995 2996 2997 2998 2999]


одного размера


In [15]:
a + b

array([ 3,  7, 11, 15, 19, 23])

In [16]:
b - a

array([1, 1, 1, 1, 1, 1])

In [17]:
a * b

array([  2,  12,  30,  56,  90, 132])

In [18]:
b / a

array([2.  , 1.33, 1.2 , 1.14, 1.11, 1.09])

In [19]:
a ** b

array([          1,          81,       15625,     5764801,  -808182895,
       -1192716655], dtype=int32)

In [20]:
b % a # При взятии остатка от деления на 0 возвращается 0

array([0, 1, 1, 1, 1, 1], dtype=int32)

In [21]:
b // a

array([2, 1, 1, 1, 1, 1], dtype=int32)

In [22]:
 np.sqrt(a)

array([1.  , 1.73, 2.24, 2.65, 3.  , 3.32])

In [23]:
np.floor(a) # к полу

np.ceil(a) # к потолку

np.rint(a) # округлить 

array([ 1.,  3.,  5.,  7.,  9., 11.])

элемент и число

In [24]:
a + 1

array([ 2,  4,  6,  8, 10, 12])

Сравнение элементов с числом!


In [25]:
a < 5

array([ True,  True, False, False, False, False])

In [26]:
a[a<5]

array([1, 3])

In [27]:
a1 = np.array([ True, False, False], bool)

In [28]:
any(a1)
all(a1)

False

In [29]:
a

array([ 1,  3,  5,  7,  9, 11])

In [30]:
np.logical_and(a > 0, a < 3)

array([ True, False, False, False, False, False])

In [31]:
a[np.logical_and(a > 0, a < 3)]

array([1])

In [32]:
np.logical_or(a > 0, a < 3)
np.logical_or(a , b)

array([ True,  True,  True,  True,  True,  True])

In [33]:
np.logical_not(a1)

array([False,  True,  True])

In [34]:
a[[0,1,0,1]]
a[[0,1],[1,1]]
a.take([0,1,3,2,0,1,3,2])
a.put([0, 2], 5)


IndexError: too many indices for array

WOW!

In [35]:
np.where(a != 2, 1 / a, a)


array([1.  , 0.33, 0.2 , 0.14, 0.11, 0.09])

In [36]:
a2 = np.array([1, np.NaN, np.Inf])
np.isnan(a2)
np.isfinite(a2)

array([ True, False, False])

In [37]:
a.sum()
np.sum(a)

36

In [38]:
a=a+1

In [39]:
a

array([ 2,  4,  6,  8, 10, 12])

In [40]:
a.prod()
np.prod(a)

46080

slice

In [41]:
a[0]
a[0:2]
a[::-1]

for i in a:
     print(i ** 2)


4
16
36
64
100
144


In [42]:
c.shape

(3, 6)

In [43]:
c

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ,  6.6 ],
       [ 7.7 ,  8.8 ,  9.9 , 10.1 , 11.11, 12.12],
       [13.13, 14.14, 15.15, 16.16, 17.17,  0.  ]])

In [44]:
c.min(axis=0)  # Наименьшее число в каждом столбце
c.min(axis=1)  # Наименьшее число в каждой строке

array([1.1, 7.7, 0. ])

In [45]:
c.argmin() # индекс минимального значения
c.min()

0.0

In [46]:
c.mean()

8.810000000000002

In [47]:
c.std()

5.152724198583374

In [48]:
c.var()

26.55056666666667

In [49]:
np.unique(c) # вывести только уникальные

array([ 0.  ,  1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ,  6.6 ,  7.7 ,  8.8 ,
        9.9 , 10.1 , 11.11, 12.12, 13.13, 14.14, 15.15, 16.16, 17.17])

In [50]:
print(c[::-1])
print('-----')
print(c[-1])

[[13.13 14.14 15.15 16.16 17.17  0.  ]
 [ 7.7   8.8   9.9  10.1  11.11 12.12]
 [ 1.1   2.2   3.3   4.4   5.5   6.6 ]]
-----
[13.13 14.14 15.15 16.16 17.17  0.  ]


In [51]:
c[1:3:1]

array([[ 7.7 ,  8.8 ,  9.9 , 10.1 , 11.11, 12.12],
       [13.13, 14.14, 15.15, 16.16, 17.17,  0.  ]])

In [52]:
print(c[2,3])
print(c[(2,3)])
print(c[2][3])

16.16
16.16
16.16


In [53]:
c[:,2]

array([ 3.3 ,  9.9 , 15.15])

In [54]:
c[:2]

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ,  6.6 ],
       [ 7.7 ,  8.8 ,  9.9 , 10.1 , 11.11, 12.12]])

In [55]:
c[1:3,1:3]

array([[ 8.8 ,  9.9 ],
       [14.14, 15.15]])

In [56]:
c

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ,  6.6 ],
       [ 7.7 ,  8.8 ,  9.9 , 10.1 , 11.11, 12.12],
       [13.13, 14.14, 15.15, 16.16, 17.17,  0.  ]])

In [57]:
c.sort()
#sorted(c)

In [58]:
k = np.array([[[10.1,10.2,10.3],[20.1,20.2,20.3],[30.1,30.2,30.3],[40.1,40.2,40.3],[50.1,50.2,50.3]],
              [[100.1,100.2,100.3],[200.1,200.2,200.3],[300.1,300.2,300.3],[400.1,400.2,400.3],[500.1,500.2,500.3]],
              [[1000.1,1000.2,1000.3],[2000.1,2000.2,2000.3],[3000.1,3000.2,3000.3],[4000.1,4000.2,4000.3],[5000.1,5000.2,5000.3]]])

In [59]:
k.shape

(3, 5, 3)

...

In [60]:
k[0:2,:,:]
k[0:2,...]

array([[[ 10.1,  10.2,  10.3],
        [ 20.1,  20.2,  20.3],
        [ 30.1,  30.2,  30.3],
        [ 40.1,  40.2,  40.3],
        [ 50.1,  50.2,  50.3]],

       [[100.1, 100.2, 100.3],
        [200.1, 200.2, 200.3],
        [300.1, 300.2, 300.3],
        [400.1, 400.2, 400.3],
        [500.1, 500.2, 500.3]]])

In [61]:
for i in k:
    print (i)
    print ('-----')
    for i2 in i:
        print (i2)
        print ('-----')
        for i3 in i2:
            print (i3)
            print ('-----')


[[10.1 10.2 10.3]
 [20.1 20.2 20.3]
 [30.1 30.2 30.3]
 [40.1 40.2 40.3]
 [50.1 50.2 50.3]]
-----
[10.1 10.2 10.3]
-----
10.1
-----
10.2
-----
10.3
-----
[20.1 20.2 20.3]
-----
20.1
-----
20.2
-----
20.3
-----
[30.1 30.2 30.3]
-----
30.1
-----
30.2
-----
30.3
-----
[40.1 40.2 40.3]
-----
40.1
-----
40.2
-----
40.3
-----
[50.1 50.2 50.3]
-----
50.1
-----
50.2
-----
50.3
-----
[[100.1 100.2 100.3]
 [200.1 200.2 200.3]
 [300.1 300.2 300.3]
 [400.1 400.2 400.3]
 [500.1 500.2 500.3]]
-----
[100.1 100.2 100.3]
-----
100.1
-----
100.2
-----
100.3
-----
[200.1 200.2 200.3]
-----
200.1
-----
200.2
-----
200.3
-----
[300.1 300.2 300.3]
-----
300.1
-----
300.2
-----
300.3
-----
[400.1 400.2 400.3]
-----
400.1
-----
400.2
-----
400.3
-----
[500.1 500.2 500.3]
-----
500.1
-----
500.2
-----
500.3
-----
[[1000.1 1000.2 1000.3]
 [2000.1 2000.2 2000.3]
 [3000.1 3000.2 3000.3]
 [4000.1 4000.2 4000.3]
 [5000.1 5000.2 5000.3]]
-----
[1000.1 1000.2 1000.3]
-----
1000.1
-----
1000.2
-----
1000.3
-----
[2000.

In [62]:
for i in k.flat:
    print (i)

10.1
10.2
10.3
20.1
20.2
20.3
30.1
30.2
30.3
40.1
40.2
40.3
50.1
50.2
50.3
100.1
100.2
100.3
200.1
200.2
200.3
300.1
300.2
300.3
400.1
400.2
400.3
500.1
500.2
500.3
1000.1
1000.2
1000.3
2000.1
2000.2
2000.3
3000.1
3000.2
3000.3
4000.1
4000.2
4000.3
5000.1
5000.2
5000.3


In [63]:
print (k)
for (x1, y1, z1, *v1) in k:
    print (x1,"|",y1,"|",z1)

[[[  10.1   10.2   10.3]
  [  20.1   20.2   20.3]
  [  30.1   30.2   30.3]
  [  40.1   40.2   40.3]
  [  50.1   50.2   50.3]]

 [[ 100.1  100.2  100.3]
  [ 200.1  200.2  200.3]
  [ 300.1  300.2  300.3]
  [ 400.1  400.2  400.3]
  [ 500.1  500.2  500.3]]

 [[1000.1 1000.2 1000.3]
  [2000.1 2000.2 2000.3]
  [3000.1 3000.2 3000.3]
  [4000.1 4000.2 4000.3]
  [5000.1 5000.2 5000.3]]]
[10.1 10.2 10.3] | [20.1 20.2 20.3] | [30.1 30.2 30.3]
[100.1 100.2 100.3] | [200.1 200.2 200.3] | [300.1 300.2 300.3]
[1000.1 1000.2 1000.3] | [2000.1 2000.2 2000.3] | [3000.1 3000.2 3000.3]


In [64]:
k.shape
'''(3, 5, 3)'''

'(3, 5, 3)'

In [65]:
k.ravel()

array([  10.1,   10.2,   10.3,   20.1,   20.2,   20.3,   30.1,   30.2,
         30.3,   40.1,   40.2,   40.3,   50.1,   50.2,   50.3,  100.1,
        100.2,  100.3,  200.1,  200.2,  200.3,  300.1,  300.2,  300.3,
        400.1,  400.2,  400.3,  500.1,  500.2,  500.3, 1000.1, 1000.2,
       1000.3, 2000.1, 2000.2, 2000.3, 3000.1, 3000.2, 3000.3, 4000.1,
       4000.2, 4000.3, 5000.1, 5000.2, 5000.3])

In [66]:
k.shape = (5, 9)
k

array([[  10.1,   10.2,   10.3,   20.1,   20.2,   20.3,   30.1,   30.2,
          30.3],
       [  40.1,   40.2,   40.3,   50.1,   50.2,   50.3,  100.1,  100.2,
         100.3],
       [ 200.1,  200.2,  200.3,  300.1,  300.2,  300.3,  400.1,  400.2,
         400.3],
       [ 500.1,  500.2,  500.3, 1000.1, 1000.2, 1000.3, 2000.1, 2000.2,
        2000.3],
       [3000.1, 3000.2, 3000.3, 4000.1, 4000.2, 4000.3, 5000.1, 5000.2,
        5000.3]])

In [67]:
k.transpose()

array([[  10.1,   40.1,  200.1,  500.1, 3000.1],
       [  10.2,   40.2,  200.2,  500.2, 3000.2],
       [  10.3,   40.3,  200.3,  500.3, 3000.3],
       [  20.1,   50.1,  300.1, 1000.1, 4000.1],
       [  20.2,   50.2,  300.2, 1000.2, 4000.2],
       [  20.3,   50.3,  300.3, 1000.3, 4000.3],
       [  30.1,  100.1,  400.1, 2000.1, 5000.1],
       [  30.2,  100.2,  400.2, 2000.2, 5000.2],
       [  30.3,  100.3,  400.3, 2000.3, 5000.3]])

In [68]:
k.reshape((5, 9), order='F')


array([[  10.1,   10.2,   10.3,   20.1,   20.2,   20.3,   30.1,   30.2,
          30.3],
       [  40.1,   40.2,   40.3,   50.1,   50.2,   50.3,  100.1,  100.2,
         100.3],
       [ 200.1,  200.2,  200.3,  300.1,  300.2,  300.3,  400.1,  400.2,
         400.3],
       [ 500.1,  500.2,  500.3, 1000.1, 1000.2, 1000.3, 2000.1, 2000.2,
        2000.3],
       [3000.1, 3000.2, 3000.3, 4000.1, 4000.2, 4000.3, 5000.1, 5000.2,
        5000.3]])

In [69]:
b

array([ 2,  4,  6,  8, 10, 12])

In [70]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.vstack((a, b))
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [71]:
np.column_stack((a, b))


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [72]:
np.row_stack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
np.hsplit(k, 3)  # Разбить на 3 части условной вертикальной линией

[array([[  10.1,   10.2,   10.3],
        [  40.1,   40.2,   40.3],
        [ 200.1,  200.2,  200.3],
        [ 500.1,  500.2,  500.3],
        [3000.1, 3000.2, 3000.3]]),
 array([[  20.1,   20.2,   20.3],
        [  50.1,   50.2,   50.3],
        [ 300.1,  300.2,  300.3],
        [1000.1, 1000.2, 1000.3],
        [4000.1, 4000.2, 4000.3]]),
 array([[  30.1,   30.2,   30.3],
        [ 100.1,  100.2,  100.3],
        [ 400.1,  400.2,  400.3],
        [2000.1, 2000.2, 2000.3],
        [5000.1, 5000.2, 5000.3]])]

In [74]:
k

array([[  10.1,   10.2,   10.3,   20.1,   20.2,   20.3,   30.1,   30.2,
          30.3],
       [  40.1,   40.2,   40.3,   50.1,   50.2,   50.3,  100.1,  100.2,
         100.3],
       [ 200.1,  200.2,  200.3,  300.1,  300.2,  300.3,  400.1,  400.2,
         400.3],
       [ 500.1,  500.2,  500.3, 1000.1, 1000.2, 1000.3, 2000.1, 2000.2,
        2000.3],
       [3000.1, 3000.2, 3000.3, 4000.1, 4000.2, 4000.3, 5000.1, 5000.2,
        5000.3]])

In [75]:
np.hsplit(k, (3, 4)) # Разбить на части условными вертикальными линиями после 3 и 4 столбца

[array([[  10.1,   10.2,   10.3],
        [  40.1,   40.2,   40.3],
        [ 200.1,  200.2,  200.3],
        [ 500.1,  500.2,  500.3],
        [3000.1, 3000.2, 3000.3]]),
 array([[  20.1],
        [  50.1],
        [ 300.1],
        [1000.1],
        [4000.1]]),
 array([[  20.2,   20.3,   30.1,   30.2,   30.3],
        [  50.2,   50.3,  100.1,  100.2,  100.3],
        [ 300.2,  300.3,  400.1,  400.2,  400.3],
        [1000.2, 1000.3, 2000.1, 2000.2, 2000.3],
        [4000.2, 4000.3, 5000.1, 5000.2, 5000.3]])]

In [76]:
np.vsplit(k, (1, 2)) # Разбить на части условными горизонтальными линиями после 1 и 2 строки

[array([[10.1, 10.2, 10.3, 20.1, 20.2, 20.3, 30.1, 30.2, 30.3]]),
 array([[ 40.1,  40.2,  40.3,  50.1,  50.2,  50.3, 100.1, 100.2, 100.3]]),
 array([[ 200.1,  200.2,  200.3,  300.1,  300.2,  300.3,  400.1,  400.2,
          400.3],
        [ 500.1,  500.2,  500.3, 1000.1, 1000.2, 1000.3, 2000.1, 2000.2,
         2000.3],
        [3000.1, 3000.2, 3000.3, 4000.1, 4000.2, 4000.3, 5000.1, 5000.2,
         5000.3]])]

In [77]:
np.vsplit(k, 5) # Разбить на 5 частей условной горизонтальной линией

[array([[10.1, 10.2, 10.3, 20.1, 20.2, 20.3, 30.1, 30.2, 30.3]]),
 array([[ 40.1,  40.2,  40.3,  50.1,  50.2,  50.3, 100.1, 100.2, 100.3]]),
 array([[200.1, 200.2, 200.3, 300.1, 300.2, 300.3, 400.1, 400.2, 400.3]]),
 array([[ 500.1,  500.2,  500.3, 1000.1, 1000.2, 1000.3, 2000.1, 2000.2,
         2000.3]]),
 array([[3000.1, 3000.2, 3000.3, 4000.1, 4000.2, 4000.3, 5000.1, 5000.2,
         5000.3]])]

In [78]:
k

array([[  10.1,   10.2,   10.3,   20.1,   20.2,   20.3,   30.1,   30.2,
          30.3],
       [  40.1,   40.2,   40.3,   50.1,   50.2,   50.3,  100.1,  100.2,
         100.3],
       [ 200.1,  200.2,  200.3,  300.1,  300.2,  300.3,  400.1,  400.2,
         400.3],
       [ 500.1,  500.2,  500.3, 1000.1, 1000.2, 1000.3, 2000.1, 2000.2,
        2000.3],
       [3000.1, 3000.2, 3000.3, 4000.1, 4000.2, 4000.3, 5000.1, 5000.2,
        5000.3]])

In [79]:
l=k # l и k это два имени для одного и того же

In [80]:
l[0,0]=0

In [81]:
k

array([[   0. ,   10.2,   10.3,   20.1,   20.2,   20.3,   30.1,   30.2,
          30.3],
       [  40.1,   40.2,   40.3,   50.1,   50.2,   50.3,  100.1,  100.2,
         100.3],
       [ 200.1,  200.2,  200.3,  300.1,  300.2,  300.3,  400.1,  400.2,
         400.3],
       [ 500.1,  500.2,  500.3, 1000.1, 1000.2, 1000.3, 2000.1, 2000.2,
        2000.3],
       [3000.1, 3000.2, 3000.3, 4000.1, 4000.2, 4000.3, 5000.1, 5000.2,
        5000.3]])

In [82]:
m=k.view() # те е данные, но изменяется представление

In [83]:
m=m.transpose()

In [84]:
m

array([[   0. ,   40.1,  200.1,  500.1, 3000.1],
       [  10.2,   40.2,  200.2,  500.2, 3000.2],
       [  10.3,   40.3,  200.3,  500.3, 3000.3],
       [  20.1,   50.1,  300.1, 1000.1, 4000.1],
       [  20.2,   50.2,  300.2, 1000.2, 4000.2],
       [  20.3,   50.3,  300.3, 1000.3, 4000.3],
       [  30.1,  100.1,  400.1, 2000.1, 5000.1],
       [  30.2,  100.2,  400.2, 2000.2, 5000.2],
       [  30.3,  100.3,  400.3, 2000.3, 5000.3]])

In [85]:
k

array([[   0. ,   10.2,   10.3,   20.1,   20.2,   20.3,   30.1,   30.2,
          30.3],
       [  40.1,   40.2,   40.3,   50.1,   50.2,   50.3,  100.1,  100.2,
         100.3],
       [ 200.1,  200.2,  200.3,  300.1,  300.2,  300.3,  400.1,  400.2,
         400.3],
       [ 500.1,  500.2,  500.3, 1000.1, 1000.2, 1000.3, 2000.1, 2000.2,
        2000.3],
       [3000.1, 3000.2, 3000.3, 4000.1, 4000.2, 4000.3, 5000.1, 5000.2,
        5000.3]])

однако

In [86]:
k [0,0]=1111

In [87]:
m

array([[1111. ,   40.1,  200.1,  500.1, 3000.1],
       [  10.2,   40.2,  200.2,  500.2, 3000.2],
       [  10.3,   40.3,  200.3,  500.3, 3000.3],
       [  20.1,   50.1,  300.1, 1000.1, 4000.1],
       [  20.2,   50.2,  300.2, 1000.2, 4000.2],
       [  20.3,   50.3,  300.3, 1000.3, 4000.3],
       [  30.1,  100.1,  400.1, 2000.1, 5000.1],
       [  30.2,  100.2,  400.2, 2000.2, 5000.2],
       [  30.3,  100.3,  400.3, 2000.3, 5000.3]])

In [88]:
n = k.copy() # настоящая копия, изменение n не влияет на k

random

In [89]:

import random

np.random.seed(1000) # фиксируем сид для одинаковой генерации рандома

np.array([random.random() for i in range(10)])


array([0.81, 0.36, 0.99, 0.51, 0.29, 0.09, 0.05, 0.98, 0.72, 0.26])

In [90]:
np.random.sample(10) # средствами numpy без аргументов возвращает просто число в промежутке [0, 1)

array([0.65, 0.12, 0.95, 0.48, 0.87, 0.21, 0.04, 0.4 , 0.23, 0.84])

In [91]:
np.random.randint(0, 3, 10)
#np.random.random_integers(0, 3, 10) # устарела
np.random.uniform(0, 3, 10)

array([0.21, 2.66, 2.86, 2.79, 1.25, 0.09, 2.95, 1.02, 2.12, 1.09])

In [92]:
o=np.random.randint(0, 7, 100)

In [93]:
o

array([2, 5, 2, 4, 0, 4, 4, 3, 1, 3, 3, 0, 6, 5, 2, 1, 3, 6, 3, 1, 5, 6,
       5, 3, 4, 5, 3, 0, 0, 2, 2, 5, 3, 1, 6, 2, 2, 3, 3, 6, 5, 0, 4, 1,
       0, 1, 1, 0, 0, 0, 2, 3, 1, 5, 3, 6, 2, 1, 6, 2, 1, 5, 0, 3, 5, 6,
       1, 6, 4, 3, 3, 6, 3, 4, 3, 5, 0, 1, 3, 5, 5, 5, 2, 0, 4, 5, 6, 4,
       1, 6, 5, 5, 6, 5, 1, 4, 1, 4, 5, 0])

In [94]:
print(np.random.shuffle(o)) # изменяет массив

None


In [95]:
o

array([0, 6, 5, 3, 3, 6, 5, 0, 2, 3, 3, 5, 3, 6, 1, 2, 5, 5, 3, 1, 2, 3,
       4, 5, 4, 4, 3, 6, 2, 6, 3, 3, 6, 3, 5, 3, 5, 1, 3, 4, 0, 4, 6, 5,
       5, 5, 0, 1, 6, 0, 1, 2, 0, 6, 4, 1, 1, 0, 4, 4, 1, 5, 2, 4, 5, 0,
       5, 1, 6, 1, 5, 3, 4, 0, 2, 4, 5, 0, 6, 1, 3, 2, 2, 1, 0, 1, 2, 5,
       5, 1, 5, 3, 1, 0, 0, 3, 3, 2, 6, 6])

numpy.random.choice(a, size=None, replace=True, p=None)

a : одномерный массив или число. Если массив, будет производиться выборка из него. Если число, то выборка будет производиться из np.arange(a).
size : размерности массива. Если None, возвращается одно значение.
replace : если True, то одно значение может выбираться более одного раза.
p : вероятности. Это означает, что элементы можно выбирать с неравными вероятностями. Если не заданы, используется равномерное распределение

In [96]:
np.random.choice(o[0:10], 10, p=[0.5, 0.25, 0.25, 0, 0, 0, 0, 0, 0, 0])

array([5, 6, 0, 0, 6, 0, 0, 0, 0, 0])

In [97]:
o.clip(2, 5) # если число меньше или равно 2 ставим 2, если число больше или равно 5 ставим 5


array([2, 5, 5, 3, 3, 5, 5, 2, 2, 3, 3, 5, 3, 5, 2, 2, 5, 5, 3, 2, 2, 3,
       4, 5, 4, 4, 3, 5, 2, 5, 3, 3, 5, 3, 5, 3, 5, 2, 3, 4, 2, 4, 5, 5,
       5, 5, 2, 2, 5, 2, 2, 2, 2, 5, 4, 2, 2, 2, 4, 4, 2, 5, 2, 4, 5, 2,
       5, 2, 5, 2, 5, 3, 4, 2, 2, 4, 5, 2, 5, 2, 3, 2, 2, 2, 2, 2, 2, 5,
       5, 2, 5, 3, 2, 2, 2, 3, 3, 2, 5, 5])

In [98]:
c

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ,  6.6 ],
       [ 7.7 ,  8.8 ,  9.9 , 10.1 , 11.11, 12.12],
       [ 0.  , 13.13, 14.14, 15.15, 16.16, 17.17]])

In [99]:
a.fill(0)
np.concatenate((a, b))
#a

array([[0, 0],
       [0, 0],
       [5, 6],
       [7, 8]])

In [100]:
b = np.array([-1., 3.], float)

ab1 = a + b
ab2 = a + b[np.newaxis,:]
ab3 = a + b[:,np.newaxis]


In [101]:
print (a)
print (b)
print (ab1)
print (ab2)
print (ab3)

[[0 0]
 [0 0]]
[-1.  3.]
[[-1.  3.]
 [-1.  3.]]
[[-1.  3.]
 [-1.  3.]]
[[-1. -1.]
 [ 3.  3.]]


In [102]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
print(np.concatenate((a,b)))
print(np.concatenate((a,b), axis=0))
print(np.concatenate((a,b), axis=1))


[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


Операции с матрицами и векторами, модуль <b>linalg</b>

In [103]:
M1=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M2=np.array([[2, 3, 4], [5, 6, 7], [8, 9, 0]])
M3=np.array([1, 2, 3, 4, 5, 6])
M4=np.array([7, 8, 9, 10, 11, 12])

In [104]:
print(M1)
print(M2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3 4]
 [5 6 7]
 [8 9 0]]


In [105]:
n=2
np.linalg.matrix_power(M1, n)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [132]:
np.dot(M1, M2) # классическое умножение матрицы - поэлементно умножить строку на столбец и сложить 
#np.dot(M1[1], M2[:,0])

array([[ 36,  42,  18],
       [ 81,  96,  51],
       [126, 150,  84]])

In [116]:
np.dot(M3, M4)

217

In [107]:
np.dot(M2, M1)

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [ 44,  61,  78]])

In [118]:
np.outer(M1, M2) # перемножение каждого элемента в 1 матрице на каждый элемент 2 матрицы (1ая строка = вытянутая 2 матрица * 1 элемент 1 матрицы)

array([[ 2,  3,  4,  5,  6,  7,  8,  9,  0],
       [ 4,  6,  8, 10, 12, 14, 16, 18,  0],
       [ 6,  9, 12, 15, 18, 21, 24, 27,  0],
       [ 8, 12, 16, 20, 24, 28, 32, 36,  0],
       [10, 15, 20, 25, 30, 35, 40, 45,  0],
       [12, 18, 24, 30, 36, 42, 48, 54,  0],
       [14, 21, 28, 35, 42, 49, 56, 63,  0],
       [16, 24, 32, 40, 48, 56, 64, 72,  0],
       [18, 27, 36, 45, 54, 63, 72, 81,  0]])

In [117]:
np.outer(M3, M4)

array([[ 7,  8,  9, 10, 11, 12],
       [14, 16, 18, 20, 22, 24],
       [21, 24, 27, 30, 33, 36],
       [28, 32, 36, 40, 44, 48],
       [35, 40, 45, 50, 55, 60],
       [42, 48, 54, 60, 66, 72]])

In [127]:
np.inner(M1, M2) # умножение матриц строка на строку, т.е. 1 элемент = сумме 
#np.dot(M1[1], M2[0])

array([[ 20,  38,  26],
       [ 47,  92,  77],
       [ 74, 146, 128]])

In [120]:
np.inner(M3, M4) # для векторов то же самое что скалярное произведение (dot product)

217

In [110]:
np.cross(M1, M2)

array([[ -1,   2,  -1],
       [ -1,   2,  -1],
       [-81,  72,  -1]])

In [124]:
print(M1[0])
print(M1[1])

[1 2 3]
[4 5 6]


In [123]:
# np.cross(M3, M4) # выдаст ошибку dimension must be 2 or 3
np.cross(M1[0], M1[1])

array([-3,  6, -3])

In [111]:
 np.linalg.det(M1)

6.66133814775094e-16

eigenvalues and eigenvectors of a matrix

In [112]:
vals, vecs = np.linalg.eig(M1)
print (vals)
print (vecs)


[ 1.61e+01 -1.12e+00 -1.30e-15]
[[-0.23 -0.79  0.41]
 [-0.53 -0.09 -0.82]
 [-0.82  0.61  0.41]]


In [113]:
np.linalg.inv(M1)

array([[-4.50e+15,  9.01e+15, -4.50e+15],
       [ 9.01e+15, -1.80e+16,  9.01e+15],
       [-4.50e+15,  9.01e+15, -4.50e+15]])

In [114]:
np.dot(M2, np.linalg.inv(M2))

array([[ 1.00e+00, -2.22e-16,  0.00e+00],
       [ 9.99e-16,  1.00e+00, -1.11e-16],
       [ 0.00e+00,  0.00e+00,  1.00e+00]])

Singular value decomposition (analogous to diagonalization of a nonsquare matrix)

In [115]:
U, s, Vh = np.linalg.svd(M1)
print (U)
print (s)
print (Vh)


[[-0.21  0.89  0.41]
 [-0.52  0.25 -0.82]
 [-0.83 -0.39  0.41]]
[1.68e+01 1.07e+00 1.47e-16]
[[-0.48 -0.57 -0.67]
 [-0.78 -0.08  0.63]
 [ 0.41 -0.82  0.41]]
